### ISSUE TITLE
How to finish install?

### ISSUE THREAD

**Issue by robrecord** [jasonsbarr/trellis-redis#1]
Many thanks for this.

Do we need to do vagrant provision or vagrant reload to get this working?

I've tried the command redis-cli but it doesn't seem to be installed.

**Comment by robrecord** [comment]
I did vagrant provision and I got an error saying that php7.1-fpm wasn't found. I edited handlers/main.yml to say php7.2-fpm but it changed itself back to php7.1-fpm upon running the command again.

I discovered I needed to change the requirements.yml to reference version 0.2.5 instead of 0.2.4

These two things should be added to the readme.

**Comment by jasonsbarr** [comment]
My apologies for the late reply, I either did not receive or simply missed the notification about the issue.

Yes, you are correct in bumping the version in requirements.yml. I must have forgotten to update the README. I've done that, and also added instructions on provisioning the box for good measure.

Thanks :)

**Comment by robrecord** [comment]
Thank you @jasonsbarr !
